# Generated by Django 5.0.7 on 2025-12-09 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('org_owner', 'Organization owner'), ('admin', 'Admin'), ('hod', 'Head of Department'), ('manager', 'Manager'), ('staff', 'Staff'), ('volunteer', 'Volunteer'), ('viewer', 'Viewer')], default='staff', max_length=32)),
                ('is_primary_admin', models.BooleanField(default=False)),
                ('scopes', models.JSONField(blank=True, default=dict, help_text='Optional scoped privileges (manager_scopes).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='church.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
