# Generated by Django 5.0.7 on 2025-12-16 10:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_alter_member_address_alter_member_baptism_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='church_memb_organiz_d88c16_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='church_memb_organiz_a5ce01_idx',
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='baptism_status',
            field=models.CharField(blank=True, choices=[('not_baptized', 'Not Baptized'), ('water_baptized', 'Water Baptized'), ('spirit_baptized', 'Spirit Baptized'), ('both', 'Both Water and Spirit Baptized')], max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_role',
            field=models.CharField(blank=True, choices=[('head', 'Family Head'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='origin_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='residential_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='residential_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='residential_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('inactive', 'Inactive'), ('visitor', 'Visitor'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='new', max_length=20),
        ),
    ]
