# Generated by Django 5.0.7 on 2025-12-17 17:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_remove_member_church_memb_organiz_d88c16_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voucher_number', models.CharField(editable=False, help_text='Auto-generated voucher number (e.g., VCH-001)', max_length=20, unique=True)),
                ('title', models.CharField(default='Funds Requisition Form', help_text='Title of the voucher request', max_length=255)),
                ('date_prepared', models.DateField(default=django.utils.timezone.now, help_text="Today's Date")),
                ('requester_name_department', models.CharField(help_text='Your Name & Department', max_length=255)),
                ('purpose', models.TextField(help_text='Reason(s) for purchasing the items / services')),
                ('urgent_items', models.TextField(blank=True, help_text='URGENT items with prices (one per line)')),
                ('important_items', models.TextField(blank=True, help_text='IMPORTANT items with prices (one per line)')),
                ('permissible_items', models.TextField(blank=True, help_text='PERMISSIBLE items with prices (one per line)')),
                ('amount_in_words', models.CharField(help_text='Total amount requested in words', max_length=500)),
                ('amount_in_figures', models.DecimalField(decimal_places=2, help_text='Total amount requested in figures', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='NGN', help_text='Currency (e.g., NGN, USD)', max_length=10)),
                ('payable_to', models.CharField(help_text='Funds are payable to (Name/Bank Account)', max_length=255)),
                ('payee_phone', models.CharField(help_text='Phone Number of Payee', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash_transfer', 'Cash or Transfer'), ('other', 'Other')], default='transfer', help_text='Preferred mode of payment', max_length=50)),
                ('needed_by', models.DateField(help_text='When is the requested fund needed')),
                ('usage_commitment', models.TextField(default='I promise that the items (or services) purchased are to be used exclusively for the organization.', help_text='Commitment to proper usage')),
                ('maintenance_commitment', models.TextField(default='I promise to keep all items in as good condition as possible at the approved location.', help_text='Commitment to maintenance')),
                ('requester_signature', models.CharField(blank=True, help_text='Department Leader Signature (name)', max_length=255)),
                ('requester_signed_date', models.DateField(blank=True, help_text='Date signed by requester', null=True)),
                ('requester_phone', models.CharField(blank=True, help_text='Phone Number for verification', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('funds_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Funds Approved', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('funds_denied', models.DecimalField(blank=True, decimal_places=2, help_text='Funds Denied', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Final approved amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_date', models.DateField(blank=True, help_text='Date approved', null=True)),
                ('finance_remarks', models.TextField(blank=True, help_text='Remarks from Finance Office')),
                ('finance_signature', models.CharField(blank=True, help_text='Signature from Finance Office', max_length=255)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually paid', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was made', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Finance/Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='church.organization')),
                ('requested_by', models.ForeignKey(help_text='User submitting the request', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_prepared', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Supporting document (quote, receipt, etc.)', upload_to='vouchers/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='church.voucher')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes not visible to requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_comments', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='church.voucher')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_number'], name='church_vouc_voucher_b0b91e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['status'], name='church_vouc_status_5f2868_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['requested_by', 'date_prepared'], name='church_vouc_request_d6d977_idx'),
        ),
    ]
