# Generated by Django 5.0.7 on 2025-12-17 20:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_voucher_voucherattachment_vouchercomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Funds Requisition Form')", max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Use as default template for organization')),
                ('church_name', models.CharField(default='Layers Of Truth', max_length=200)),
                ('church_motto', models.CharField(blank=True, default='Unveiling Christ, Communicating Eternal Life.', max_length=500)),
                ('form_title', models.CharField(default='Funds Requisition Form', max_length=200)),
                ('description', models.TextField(blank=True, default='This form is used to request for funding already approved by the department.')),
                ('warning_text', models.TextField(blank=True, default='YOU MUST BE THE LEADER OF A COMMUNITY / DEPARTMENT TO REQUEST FUNDING.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='voucher_logos/')),
                ('show_urgent_items', models.BooleanField(default=True)),
                ('show_important_items', models.BooleanField(default=True)),
                ('show_permissible_items', models.BooleanField(default=True)),
                ('signature_label', models.CharField(default='Department Leader Signature', max_length=200)),
                ('date_label', models.CharField(default='Date', max_length=200)),
                ('phone_label', models.CharField(default='Phone Number', max_length=200)),
                ('footer_text', models.TextField(blank=True, help_text='Text to display at bottom of form')),
                ('finance_section_title', models.CharField(default='CHURCH OFFICE USE ONLY', max_length=200)),
                ('finance_office_name', models.CharField(default='Finance Office', max_length=200)),
                ('default_usage_commitment', models.TextField(default='I promise that the items (or services) purchased are to be used exclusively for the organization.')),
                ('default_maintenance_commitment', models.TextField(default='I promise to keep all items in as good condition as possible at the approved location.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_templates', to='church.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='church.vouchertemplate'),
        ),
    ]
