# Generated by Django 5.0.7 on 2025-12-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_vouchertemplate_voucher_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='requester_signature_image',
            field=models.ImageField(blank=True, help_text='Signature image (drawn/uploaded)', null=True, upload_to='voucher_signatures/%Y/%m/%d/'),
        ),
    ]
