# Generated by Django 5.0.7 on 2025-12-18 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_voucher_requester_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount_in_figures',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount requested in figures', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='currency',
            field=models.CharField(blank=True, default='NGN', help_text='Currency (e.g., NGN, USD)', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash_transfer', 'Cash or Transfer'), ('other', 'Other')], default='transfer', help_text='Preferred mode of payment', max_length=50),
        ),
    ]
