# Generated by Django 5.0.7 on 2025-12-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_alter_voucher_amount_in_figures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='needed_by',
            field=models.DateField(blank=True, help_text='When is the requested fund needed', null=True),
        ),
    ]
