# Generated by Django 5.0.7 on 2025-12-19 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_category_location_item_audit_purchaseorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audititem',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='audititem',
            name='counted_by',
        ),
        migrations.RemoveField(
            model_name='audititem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='audititem',
            name='stock_entry',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='item',
            name='primary_location',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='location',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='location',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='expected_location',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='stock_entry',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock_entries',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference_document',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='organization',
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('audit_type', models.CharField(choices=[('full', 'Full Inventory Audit'), ('spot', 'Spot Check'), ('cycle', 'Cycle Count'), ('department', 'Department Audit')], max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('items_checked', models.IntegerField(default=0)),
                ('discrepancies_found', models.IntegerField(default=0)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_inventory_audits', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audits', to='church.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audits', to='church.organization')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_inventory_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('worship', 'Worship Supplies'), ('event', 'Event Equipment'), ('office', 'Office Supplies'), ('maintenance', 'Maintenance'), ('kitchen', 'Kitchen Supplies'), ('technology', 'Technology'), ('furniture', 'Furniture'), ('seasonal', 'Seasonal Decorations'), ('other', 'Other')], default='other', max_length=20)),
                ('color_code', models.CharField(default='#6c757d', help_text='Hex color for UI display', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='church.organization')),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['category_type', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('consumable', 'Consumable (Communion, candles, etc.)'), ('equipment', 'Equipment (Sound, projectors, etc.)'), ('asset', 'Capital Asset (Expensive, long-term)'), ('furniture', 'Furniture'), ('supply', 'General Supply'), ('resource', 'Resource (Books, media)')], default='supply', max_length=20)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit', max_length=100)),
                ('asset_tag', models.CharField(blank=True, help_text='For tracking capital assets', max_length=100, null=True, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Barcode/QR code identifier', max_length=50, null=True, unique=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('alert_on_low', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('repair', 'Needs Repair'), ('retired', 'Retired/Disposed')], default='good', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Specific location (Room, Shelf, Bin)', max_length=200)),
                ('storage_instructions', models.TextField(blank=True, help_text='Special storage requirements')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_items/%Y/%m/')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_audited', models.DateField(blank=True, null=True)),
                ('last_checked_out', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='church.inventorycategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='church.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='church.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purpose', models.CharField(blank=True, help_text='What will this be used for?', max_length=200)),
                ('event_name', models.CharField(blank=True, help_text='Related church event', max_length=100)),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('returned', 'Returned'), ('lost', 'Lost'), ('damaged', 'Damaged')], default='active', max_length=20)),
                ('returned_quantity', models.IntegerField(default=0)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('returned_condition', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('repair', 'Needs Repair'), ('retired', 'Retired/Disposed')], max_length=20)),
                ('return_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inventory_checkouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_checkouts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='church.department')),
                ('member', models.ForeignKey(help_text='Church member checking out item', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checkouts', to='church.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checkouts', to='church.organization')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='church.inventoryitem')),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.IntegerField()),
                ('counted_quantity', models.IntegerField()),
                ('difference', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('adjusted', models.BooleanField(default=False)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='church.inventoryaudit')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('overdue', 'Overdue Checkout'), ('audit', 'Audit Required'), ('maintenance', 'Maintenance Due'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_notifications', to='church.organization')),
                ('related_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.inventorycheckout')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Stock Added'), ('remove', 'Stock Removed'), ('transfer', 'Department Transfer'), ('checkout', 'Checked Out'), ('return', 'Returned'), ('adjust', 'Audit Adjustment'), ('write_off', 'Write Off'), ('damage', 'Damaged/Lost')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='PO Number, Receipt #, etc.', max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='church.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='church.inventoryitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='church.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='church.department')),
                ('voucher', models.ForeignKey(blank=True, help_text='Related voucher for purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='church.voucher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_vendors', to='church.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='church.inventoryvendor'),
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='AuditItem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.DeleteModel(
            name='StockEntry',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddIndex(
            model_name='inventorycheckout',
            index=models.Index(fields=['status'], name='church_inve_status_843978_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckout',
            index=models.Index(fields=['due_date'], name='church_inve_due_dat_7dba26_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckout',
            index=models.Index(fields=['member', 'status'], name='church_inve_member__7c463c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryaudititem',
            unique_together={('audit', 'item')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='church_inve_created_ddc515_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='church_inve_transac_e266df_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item', 'created_at'], name='church_inve_item_id_9684c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryvendor',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='church_inve_sku_bbdf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='church_inve_barcode_7d7fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['department'], name='church_inve_departm_e6a48c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_type'], name='church_inve_item_ty_8e6cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['condition'], name='church_inve_conditi_eb2caf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active'], name='church_inve_is_acti_77aac6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', 'quantity'], name='church_inve_organiz_383d29_idx'),
        ),
    ]
