"""
Django settings for sanctuary project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vp#h079ebsb31%4162l)o&n43n6n%xx+_#s=)v-9(4!c8&=mqc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # local apps
    "accounts",
    "church",

    # third-party
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "phonenumber_field",
    "django.contrib.humanize",



]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sanctuary.urls'

# custom user model
AUTH_USER_MODEL = "accounts.User"


BASE_DIR = Path(__file__).resolve().parent.parent


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Add this
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # you can keep SessionAuthentication for admin web if desired
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",    # For mobile ← ADD THIS

    ),
}

WSGI_APPLICATION = 'sanctuary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
## settings.py
# ... existing code ...

# Email settings - UPDATED
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'sanctuarytechn@gmail.com'
EMAIL_HOST_PASSWORD = 'mwurkeduqybugmqy'  # This might be wrong format
DEFAULT_FROM_EMAIL = 'Sanctuary Platform <sanctuarytechn@gmail.com>'
EMAIL_USE_SSL = False

# Platform settings - FIXED (remove duplicates)
SITE_URL = 'http://localhost:3000'  # Your frontend URL
FRONTEND_INVITE_URL = 'http://localhost:3000/invite'  # Frontend invite page
PLATFORM_NAME = 'Sanctuary Church Platform'
ADMIN_EMAIL = 'sanctuarytechn@gmail.com'  # Change this to your admin email
ORGANIZATION_REGISTRATION_FEE = 99.00

# ... rest of settings ...

# Frontend URL used to build invite links (frontend will handle /invite/accept?token=)
FRONTEND_INVITE_URL = "http://localhost:3000/invite"  # change to your real frontend URL in prod

# Fallback SITE_URL used when FRONTEND_INVITE_URL not set
SITE_URL = "http://localhost:8000"

# ---------------------------------------------------------------------
# SimpleJWT sensible defaults (you already added JWT auth to REST_FRAMEWORK)
# (install with: pip install djangorestframework-simplejwt)
# ---------------------------------------------------------------------
from datetime import timedelta
SIMPLE_JWT = {
    'USER_ID_FIELD': 'uid', 
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}
# ---------------------------------------------------------------------
# Security / operational notes
# ---------------------------------------------------------------------
# - In production, set EMAIL_BACKEND to SMTP and provide EMAIL_HOST/EMAIL_HOST_USER/EMAIL_HOST_PASSWORD via environment variables.
# - Use a verified sending domain (SPF/DKIM/DMARC) for good deliverability.
# - Never commit real SMTP credentials or API keys to the repo. Use environment variables or secret manager.
